version: '3.9'
services:
  cloudflare-ddns:
    image: cloudflare-ddns
    container_name: cloudflare-ddns
    build: ..
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config.json:/config.json
    restart: unless-stopped
